### ISSUE TITLE
Pull Requests/Issues link are not identified

### ISSUE THREAD

**Issue by pacospace** [AICoE/SrcOpsMetrics#83]
**Describe the bug**
Referenced Issues of Pull Requests are not identified.

**To Reproduce**
1. Run `PYTHONPATH=. GITHUB_ACCESS_TOKEN=<acces_token> pipenv run python3 srcopsmetrics/cli.py --repository thoth-station/performance -c -l`
2. There are PR with Fixes in the comment but they are not identified.

**Expected behavior**
The referenced issue relative to a PR are identified.

**Comment by xtuchyna** [comment]
catched that! :)
the problem was that i was just inspecting the comments in pull request, however - the first comment in pr is not a comment itself, but a *body* attribute of pull request.

Also, the referenced issue id was not in url format (as it normally was in comments) but rather a raw string as #<issue_id> was part of the body message.
